server:
  port: 8000

spring:
  application:
    name:
      ms-shipping-status
  data:
    mongodb:
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: shalom-status
      authentication-database: admin

configuration:
  verifyStatusTask: "0 0/25 8-20 * * *"
  defaultMessagesMailConfig: ${DEFAULT_MSG_MAIL}
  apis:
    shalom: ${REST_CLIENT_SHALOM}