server:
  port: 8000

spring:
  application:
    name:
      ms-shipping-status
  data:
    mongodb:
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: shalom-status
      authentication-database: admin
  mail:
    port: 587
    host: smtp.gmail.com
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true

configuration:
  verifyStatusTask: "0 0/25 8-20 * * *"
  defaultMessagesConfig: ${DEFAULT_MSG}
  defaultStepMessagesConfig: ${DEFAULT_STEP_MSG}
  apis:
    shalom: ${REST_CLIENT_SHALOM}