name: Deploy to VPS

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    env:
      image_name: ms-shipping-status
      image_version: latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build project and verify test
        run: mvn clean install

      - name: Push image DOCKER
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}
          tags: ${{ env.image_version }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/administrator/applications/shipping-shalom
            echo ${{ secrets.VPS_PASSWORD }} | sudo docker stop ${{ env.image_name }}
            echo ${{ secrets.VPS_PASSWORD }} | sudo docker rm ${{ env.image_name }}
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:${{ env.image_version }}
            echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker compose up -d --build
            echo y | echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker system prune -a